POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "mmyildiz97@gmail.com",
    "password": "ByOtIX8QfK"
}

###

POST {{baseUrl}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "meryem merve",
    "surName": "yıldız",
    "email": "mmyildiz97@gmail.com",
    "password": "password",
    "phone":"5685865555",
    "userType":"Admin",
    "birthyear": "1995",
    "identityNo": "1000000000"
}

###


PUT {{baseUrl}}/change-password HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "password": "meryemx",
    "newPassword": "merve"
}

###


POST {{baseUrl}}/forgot-password HTTP/1.1
Content-Type: application/json

{
    "email": "mmyildiz97@gmail.com"
}

###

PUT {{baseUrl}}/reset-password HTTP/1.1
Content-Type: application/json

{
    "email": "mmyildiz97@gmail.com",
    "recoveryCode": "ByOtIX8QfK",
    "newPassword": "meryem"
}

###

GET {{baseUrl}}/token-decode HTTP/1.1
Content-Type: application/json
token: {{token}}
